app/blueprints/__init__.py
from .home import home
from .uploader import uploader

app/blueprints/home/__init__.py
from .blueprint import home

app/blueprints/home/blueprint.py
from flask import Blueprint, render_template, request
import psycopg2

home = Blueprint('home', __name__)


WRONG_PICTURES = []


@home.route('/',  methods=['POST', 'GET'])
def route_name():
    if request.method == 'GET':
        return render_template('home.html', feedback=False)
    else:
        text = request.form['text']
        WRONG_PICTURES.append(text)
        print(WRONG_PICTURES)
        # save_into_db(text)
        return render_template('home.html', feedback=True)


def create_pictures_table():
    conn = psycopg2.connect(
        user="felix", database="tiki", password="felixpostgre")
    conn.autocommit = True
    cursor = conn.cursor()

    query = """
        CREATE TABLE IF NOT EXISTS pictures(
            name VARCHAR(255)
            );
    """
    try:
        cursor.execute(query)
    except Exception as err:
        print(f'ERROR: {err}')
    cursor.close()


def save_into_db(name_of_picture):
    conn = psycopg2.connect(
        user="felix", database="tiki", password="felixpostgre")
    conn.autocommit = True
    cursor = conn.cursor()
    query = f"""INSERT INTO pictures (name) 
            VALUES (%s);"""
    val = (name_of_picture)
    print(
        f'name: {name_of_picture}')
    try:
        cursor.execute(query, val)
    except Exception as err:
        print(f'ERROR: {err}')
    cursor.close()


create_pictures_table()

app/blueprints/uploader/__init__.py
from .blueprint import uploader

app/blueprints/uploader/blueprint.py
from flask import Blueprint, render_template, request, redirect, send_from_directory
from keras.preprocessing.image import load_img, img_to_array
from werkzeug import secure_filename
import tensorflow as tf
import numpy as np
import os

UPLOAD_FOLDER = 'uploads'

model = tf.keras.models.load_model('models/model.h5')

uploader = Blueprint('uploader', __name__)

IMAGE_SIZE = 128


@uploader.route('/uploader', methods=['GET', 'POST'])
def upload():
    # get file
    uploaded_file = request.files['file']

    # check if file is an image
    if uploaded_file.content_type != "image/jpeg":
        return redirect("/")

    # create path of image
    upload_image_path = os.path.join("uploads", uploaded_file.filename)

    # save image
    uploaded_file.save(upload_image_path)
    # classify image
    probability = classify(upload_image_path)

    return render_template('home.html', probability=probability, filename=uploaded_file.filename)


def classify(upload_image_path):

    image = tf.io.read_file(upload_image_path)
    image = tf.image.decode_jpeg(image, channels=3)
    image = tf.image.resize(image, [IMAGE_SIZE, IMAGE_SIZE])
    image /= 255.0  # normalize to [0,1] range
    image = tf.reshape(image, (1, IMAGE_SIZE, IMAGE_SIZE, 3))
    probability = model.predict(image)

    if probability[0][0] > probability[0][1]:
        return {"cat": round((probability[0][0] * 100), 2)}
    else:
        return {"dog": round((probability[0][1] * 100), 2)}


@uploader.route('/uploader/<filename>')
def send_file(filename):
    return send_from_directory("uploads", filename)

app/main.py
from flask import Flask, render_template
from blueprints import *

app = Flask(__name__)
app.register_blueprint(home)
app.register_blueprint(uploader)

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5001, debug=True)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Cat or Dog?</title>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link rel="shortcut icon" type="image/png" href="static/images/fav.jpg" />
    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <!-- CSS -->
    <link href="static/css/style.css" rel="stylesheet" />
  </head>
  <body class="text-center">
    {% block content%} {% endblock %}

    <script src="static/js/jquery-3.4.1.min.js"></script>
    <script src="static/js/index.js"></script>
    <script type="text/javascript"></script>
  </body>
</html>

app/templates/home.html
{% extends "base.html" %} {% block content %}
<div style="margin-top:50px">
  <img class="mb-4" src="static/images/coderschool-logo.png" alt="" />
  <div></div>
  {% if feedback %}
  <div class="alert alert-success fade show" role="alert" style="margin:20px 100px">
    <strong>Thank you for your feedback!</strong> Our model will be improved soon.
  </div>
  {% endif%}


  {% if probability %}
  <div style="margin-bottom:60px;" class="animated bounce animation-duration: 1s;">  
    {% if probability.cat %}
    <img src="static/images/cat.png" alt="">
    
    <div class="category">{{probability.cat}}%</div class="category">
    {% else %}
    <img src="static/images/dog.png" alt="">

    <div class="category">{{probability.dog}}%</div>
    {% endif %}
  </div>
  <form action="/" method="POST" enctype="multipart/form-data">
    <input name="text" value="{{filename}}" class="d-none">
    <input type="submit" class="wrong" value="Wrong answer?" id="snd" style="opacity: 0.5;margin-top:30px; border: none;
    background: transparent;
    border-bottom: 1px solid #fff;
    outline: none;"/>
  </form>

  
  {% endif%}


  {% if filename %}


  <img
    class="pred_img"
    style="max-height:200px; margin:50px; border-radius: 5px"
    src="{{ url_for('uploader.send_file', filename=filename)}}"
  />

  {% else %}
  <img
    id="catOrDog"
    src="static/images/catordog.jpg"
    alt="cat or dog"
    style="max-height:360px; margin:50px; border-radius: 5px"
  />

  {% endif %}

  <form action="/uploader" method="POST" enctype="multipart/form-data">
    <input type="file" id="file" name="file" />
    <div class="new_Btn" style="width: 180px;">
      <div class="text-select">Select a picture</div> 
      <div class="spinner-border text-light d-none" role="status">
        <span class="sr-only">Loading...</span>
      </div></div>
    </div>
    <input type="submit" class="button" value="Send" id="send" />
  </form>
</div>
{% endblock %}

app/templates/upload.html
{% extends "base.html" %} {% block content %}
<div>upload</div>
{% endblock %}